#!/bin/bash

function last_rib()
{
	tail ${tmpdir}/index.html | grep rib\. | tail -n 1 | \
	awk -F 'href="' '{print $2}' | \
	sed -e 's/".*//'
}

function get_i2_netblocks()
{
    URL='http://syslog.abilene.ucaid.edu/bgp/WASH/RIBS'
    tmpdir=$(mktemp -d /tmp/get_i2_netblocks.XXXXXXXX) || exit 1
    trap "rm -rf ${tmpdir}" EXIT QUIT HUP KILL TERM
    wget -q -O ${tmpdir}/index.html "${URL}/"
    last=$(last_rib)
    wget -O ${tmpdir}/rib.gz -q "${URL}/$last"
    zcat ${tmpdir}/rib.gz | perl internet2/zebra-dump-parser/zebra-dump-parser.pl
}

get_i2_netblocks
