#!/bin/bash

echo "=============================================================="
echo -n "Starting at "
date

MM_DIR=/srv/tg/mirrormanager
MIRRORLIST_DIR=${MM_DIR}/mirrorlists
LOCKFILE=/tmp/mirrormanager-update-all.lock

[ -e ${LOCKFILE} ] && kill -0 $(cat ${LOCKFILE}) && exit 2
echo $$ > ${LOCKFILE}
trap "rm -f ${LOCKFILE}" QUIT TERM INT HUP EXIT

cd ${MM_DIR}

function get_rsync_lists()
{
    local REPOS
    REPOS[0]='/pub/fedora/linux/core'
    REPOS[1]='/pub/fedora/linux/extras'
    REPOS[2]='/pub/epel'
    REPOS[3]='/pub/fedora/web'
    REPOS[4]='/pub/fedora/linux'
    local FILES
    FILES[0]='fedora-linux-core.txt'
    FILES[1]='fedora-linux-extras.txt'
    FILES[2]='fedora-epel.txt'
    FILES[3]='fedora-web.txt'
    FILES[4]='fedora-linux.txt'
    local EXCLUDES
    EXCLUDES[4]='--exclude=core/ --exclude=extras/'
    local i=0
    while [ $i -lt ${#FILES[@]} ]; do
	pushd ${REPOS[$i]} > /dev/null 2>&1
	rsync -r ${EXCLUDES[$i]} . > /tmp/${FILES[$i]}
	popd > /dev/null 2>&1
	i=$(($i + 1))
    done
}


get_rsync_lists
echo -n "get_rsync_lists finished at "
date
./update-master-directory-list prod.cfg
./crawler -c prod.cfg --threads 15 | bash

echo -n "Ending at "
date
