#!/bin/bash

MM_DIR=/srv/tg/mirrormanager
MIRRORLIST_DIR=${MM_DIR}/mirrorlists
LOCKFILE=/tmp/mirrormanager-update-each-server.lock

[ -e ${LOCKFILE} ] && kill -0 $(cat ${LOCKFILE}) && exit 2
echo $$ > ${LOCKFILE}
trap "rm -f ${LOCKFILE}" QUIT TERM INT HUP EXIT

cd ${MM_DIR}
MIRRORLIST_DIR=${MIRRORLIST_DIR} ./update-static-content

./refresh_mirrorlist_cache -c prod.cfg
./get_internet2_netblocks > /tmp/mirrormanager_i2_netblocks.txt
killall -HUP mirrorlist_server.py
