#!/bin/bash

[ -z "${MIRRORLIST_DIR}" ] && exit 1


temp_dir_name=`mktemp -d /tmp/mirrorlists.XXXXXX`

./generate-mirrorlists -c prod.cfg -d $temp_dir_name
pushd $temp_dir_name > /dev/null 2>&1
# don't use --mirror because it turns on timestamping, which causes
# an extra HEAD request for each page, which to cherrypy just causes
# twice as many database lookups.
wget -nH --cut-dirs=1 -r -l inf --no-remove-listing http://localhost:8082/mirrormanager/publiclist

rsync -va ${MIRRORLIST_DIR}/../mirrors/static .
touch robots.txt
# remove /mirrormanager in the URLs
find . -name index.html -type f | xargs -n 20 perl -p -i -e 's:/mirrormanager/:/:g'
popd > /dev/null 2>&1
mkdir -p ${MIRRORLIST_DIR}
# because the arg list is too long for cp
rsync -a --delete --delete-after --delay-updates $temp_dir_name/ ${MIRRORLIST_DIR}/
rm -rf $temp_dir_name
