#!/bin/bash

MM_DIR=/srv/tg/mirrormanager
MIRRORLIST_DIR=${MM_DIR}/mirrorlists
LOCKFILE=/tmp/mirrormanager-update-all.lock

[ -e ${LOCKFILE} ] && kill -0 $(cat ${LOCKFILE}) && exit 2
echo $$ > ${LOCKFILE}
trap "rm -f ${LOCKFILE}" QUIT TERM INT HUP EXIT

cd ${MM_DIR}
MIRRORLIST_DIR=${MIRRORLIST_DIR} ./update-static-content

wget -O - 'http://127.0.0.1:8082/mirrormanager/refresh_mirrorlist_cache' > /dev/null 2>&1
wget -O - 'http://127.0.0.1:8082/mirrormanager/dump_mirrorlist_cache' > /dev/null 2>&1
