#!/bin/bash

echo "=============================================================="
echo -n "Starting at "
date

MM_DIR=/srv/tg/mirrormanager
MIRRORLIST_DIR=${MM_DIR}/mirrorlists
LOCKFILE=/tmp/mirrormanager-update-all.lock

[ -e ${LOCKFILE} ] && kill -0 $(cat ${LOCKFILE}) && exit 2
echo $$ > ${LOCKFILE}
trap "rm -f ${LOCKFILE}" QUIT TERM INT HUP EXIT

cd ${MM_DIR}

function get_rsync_lists()
{
    local REPOS
    REPOS[0]='/pub/fedora/linux/core'
    REPOS[1]='/pub/fedora/linux/extras'
    REPOS[2]='/pub/epel'
    local FILES
    FILES[0]='fedora-linux-core.txt'
    FILES[1]='fedora-linux-extras.txt'
    FILES[2]='fedora-epel.txt'
    local i=0
    while [ $i -lt ${#FILES[@]} ]; do
	pushd ${REPOS[$i]} > /dev/null 2>&1
	rsync -r . > /tmp/${FILES[$i]}
	popd > /dev/null 2>&1
	i=$(($i + 1))
    done
}

function get_rsync_lists_from_files()
{
    local FILES="fedora-linux-core.txt fedora-linux-extras.txt fedora-epel.txt"
    local SERVER="http://linux.dell.com/files/fedora/rsync"
    
    pushd /tmp
    for f in ${FILES}; do
	rm $f
	wget "${SERVER}/$f.bz2"
	bunzip2 $f.bz2
    done
    popd
}

get_rsync_lists
echo -n "get_rsync_lists finished at "
date
./update-master-directory-list dev-postgres.cfg
./crawler -c dev-postgres.cfg | bash
MIRRORLIST_DIR=${MIRRORLIST_DIR} ./update-static-content

wget -O - 'http://127.0.0.1:8082/mirrormanager/refresh_mirrorlist_cache' > /dev/null 2>&1

echo -n "Ending at "
date
