#!/usr/bin/python
from optparse import OptionParser
import sys, re

__requires__ = 'TurboGears[future]'
import pkg_resources
pkg_resources.require("TurboGears")

import turbogears
from turbogears.database import PackageHub
from mirrormanager.initial import user_group_setup, create_arches

hub = __connection__ = None
options = None

def doit():
    user_group_setup()
    create_arches()

def main():
    global options
    parser = OptionParser(usage=sys.argv[0] + " [options]")
    parser.add_option("-c", "--config",
                      dest="config", default='/etc/mirrormanager/prod.cfg',
                      help="TurboGears config file to use (default=/etc/mirrormanager/prod.cfg)")

    (options, args) = parser.parse_args()

    turbogears.update_config(configfile=options.config,
                             modulename="mirrormanager.config")
    global hub
    global __connection__
    hub = PackageHub("mirrormanager")
    __connection__ = hub
    
    doit()
    return 0

if __name__ == "__main__":
    sys.exit(main())
        
