#!/usr/bin/python
__requires__ = 'TurboGears[future]'
import pkg_resources
pkg_resources.require("TurboGears")

import sys, re, os
from optparse import OptionParser
from sqlobject import *
import turbogears
sys.path.append('/usr/share/mirrormanager/server')
from mirrormanager.model import Category, Directory

from turbogears.database import PackageHub
hub = __connection__ = None

options = None

# moving from pub/fedora/linux/development/14/x86_64/os to pub/fedora/linux/releases/14/Everything/x86_64/os


def doit():
    global options
    try:
        c = Category.byName(options.category)
    except SQLObjectNotFound:
        sys.stderr.write("Category '%s' not found, exiting" % options.category)
        print_categories(sys.stderr)
        sys.stderr.flush()
        sys.exit(1)
    topdir = c.topdir.name
    oldpattern = os.path.join('development', options.version)
    newpattern = os.path.join('releases', options.version, 'Everything')
    oldRe = re.compile(oldpattern)
    for d in c.directories:
        if oldRe.search(d.name):
            for r in d.repositories:
                t = d.name.replace(oldpattern, newpattern)
                try:
                    new_d = Directory.byName(t)
                except SQLObjectNotFound:
                    sys.stderr.write("target Directory(%) not found, ignoring.\n")
                    sys.stderr.flush()
                    break
                    
                try:
                    r.directory = new_d
                    r.category = c
                    r.sync()
                    print "%s => %s" % (d.name, t)
                except:
                    raise

def print_categories(fileno):
    fileno.write("Available categories:\n")
    for c in Category.select():
        fileno.write("\t%s\n" % c.name)
        fileno.flush()

def main():
    global options
    parser = OptionParser(usage=sys.argv[0] + " [options]")
    parser.add_option("-c", "--config",
                      dest="config", default='/etc/mirrormanager/prod.cfg',
                      help="TurboGears config file to use (default=/etc/mirrormanager/prod.cfg)")
    parser.add_option("--version",
                      dest="version", action="store", type="string", help="OS version to move (e.g. '14') [required]", default=None)
    parser.add_option("--category",
                      dest="category", action="store", type="string", help="Category (e.g. 'Fedora Linux') [required]", default=None)

    (options, args) = parser.parse_args()
    if options.version is None or options.category is None:
        parser.print_help()
        print_categories(sys.stdout)
        sys.exit(1)

    turbogears.update_config(configfile=options.config,
                             modulename="mirrormanager.config")
    global hub
    global __connection__
    hub = PackageHub("mirrormanager")
    __connection__ = hub
    
    doit()
    return 0

if __name__ == "__main__":
    sys.exit(main())
        
