#!/usr/bin/python
__requires__ = 'TurboGears[future]'
import pkg_resources
pkg_resources.require("TurboGears")

import sys
import optparse
import turbogears
from turbogears.database import PackageHub
sys.path.append('/usr/share/mirrormanager/server')
from mirrormanager.mirrorlist import populate_all_caches, dump_caches

hub = __connection__ = None
options = None

def doit():
    global options
    populate_all_caches()
    dump_caches(options.output)

def main():
    global options
    parser = optparse.OptionParser(usage=sys.argv[0] + " [options]")
    parser.add_option("-c", "--config",
                      dest="config", default='dev.cfg',
                      help="TurboGears config file to use")
    parser.add_option("-o", "--output",
                      dest="output", default='/var/lib/mirrormanager/mirrorlist_cache.pkl',
                      help="output file")

    (options, args) = parser.parse_args()

    turbogears.update_config(configfile=options.config,
                             modulename="mirrormanager.config")
    global hub
    global __connection__
    hub = PackageHub("mirrormanager")
    __connection__ = hub
    
    doit()
    return 0


if __name__ == "__main__":
    sys.exit(main())
        
