#!/usr/bin/python
__requires__ = 'TurboGears[future]'
import pkg_resources
pkg_resources.require("TurboGears")

from optparse import OptionParser
import sys
from sqlobject import *
import turbogears
from mirrormanager.model import *

from turbogears.database import PackageHub
hub = __connection__ = None

options = None


def main():
    global options
    parser = OptionParser(usage=sys.argv[0] + " [options]")
    parser.add_option("-c", "--config",
                      dest="config", default='/etc/mirrormanager/prod.cfg',
                      help="TurboGears config file to use (default=/etc/mirrormanager/prod.cfg)")

    (options, args) = parser.parse_args()

    turbogears.update_config(configfile=options.config,
                             modulename="mirrormanager.config")
    global hub
    global __connection__
    hub = PackageHub("mirrormanager")
    __connection__ = hub
    
    import mirrormanager.schema_updates
    mirrormanager.schema_updates.update()
    return 0

if __name__ == "__main__":
    sys.exit(main())
        
