ALTER TABLE arch ADD COLUMN primary_arch BOOL DEFAULT FALSE;
ALTER TABLE arch ADD COLUMN publiclist BOOL DEFAULT TRUE;
ALTER TABLE directory ADD COLUMN ctime BIGINT DEFAULT 0;
ALTER TABLE file_detail ADD COLUMN sha256 TEXT DEFAULT NULL;
ALTER TABLE file_detail ADD COLUMN sha512 TEXT DEFAULT NULL;
UPDATE arch SET primary_arch=FALSE, publiclist=TRUE;
UPDATE directory SET ctime=0;
UPDATE file_detail SET sha256=NULL, sha512=NULL;
